name: Release

on:
  push:
    tags:
      - 'v*'  # Запускать при создании тегов вида v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      working-directory: ./build
      run: cmake ..

    - name: Build project
      working-directory: ./build
      run: cmake --build . --config Release

    - name: Run tests
      working-directory: ./build
      run: ./tests

    - name: Generate DEB package
      working-directory: ./build
      run: cpack

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: build/*.deb

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: deb-package
        path: artifacts

    - name: Create Release
      uses: actions/create-release@v2
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        body: |
          Automatic release for version ${{ github.ref_name }}
          DEB package attached
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v2
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./artifacts/*.deb
        asset_name: rk2-patterns.deb
        asset_content_type: application/vnd.debian.binary-package
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
